use std::fs;
use std::path::Path;

fn main() {
    generate_nsis_hooks();
    tauri_build::build()
}

/// Generate windows/hooks.nsi with DLL delete list derived from installers/dlls/*.dll.
fn generate_nsis_hooks() {
    let dlls_dir = Path::new("installers/dlls");
    let hooks_path = Path::new("windows/hooks.nsi");

    // Collect DLL filenames, sorted for deterministic output
    let mut dlls: Vec<String> = Vec::new();
    if dlls_dir.is_dir() {
        for entry in fs::read_dir(dlls_dir).expect("failed to read installers/dlls") {
            let entry = entry.expect("failed to read dir entry");
            let name = entry.file_name().to_string_lossy().to_string();
            if name.to_lowercase().ends_with(".dll") {
                dlls.push(name);
            }
        }
    }
    dlls.sort();

    // Build the Delete lines for PREUNINSTALL
    let delete_lines: String = dlls
        .iter()
        .map(|dll| format!("    Delete \"$INSTDIR\\{}\"", dll))
        .collect::<Vec<_>>()
        .join("\n");

    let hooks = format!(
        r#"; Sacho NSIS Installer Hooks — generated by build.rs, do not edit by hand
; DLL delete list is built from installers/dlls/*.dll at compile time

; ============================================================================
; PREINSTALL - Runs before any files are copied
; ============================================================================
!macro NSIS_HOOK_PREINSTALL
    ; Nothing needed here
!macroend

; ============================================================================
; POSTINSTALL - Runs after all files are copied but before shortcuts are created
; ============================================================================
!macro NSIS_HOOK_POSTINSTALL
    ; Copy GStreamer DLLs from the bundled resources to the application directory
    ; These DLLs must be in the same directory as the exe for Windows to find them at startup
    DetailPrint "Copying GStreamer runtime libraries..."

    FindFirst $0 $1 "$INSTDIR\installers\dlls\*.dll"
    ${{IfNot}} ${{Errors}}
        loop_copy:
            CopyFiles /SILENT "$INSTDIR\installers\dlls\$1" "$INSTDIR"
            FindNext $0 $1
            ${{IfNot}} ${{Errors}}
                Goto loop_copy
            ${{EndIf}}
        FindClose $0
    ${{EndIf}}

    DetailPrint "GStreamer runtime libraries installed successfully"

    ; Remove the installers folder after copying (no longer needed)
    RMDir /r "$INSTDIR\installers"

    ; ---- Autostart registration ----
    ; Write to HKLM for all-users installs, HKCU for per-user installs.
    ; Never write both -- Windows processes both Run keys on boot, which
    ; would launch two instances and the single-instance handler would
    ; immediately show the hidden window.
    !if "${{INSTALLMODE}}" == "both"
    ${{If}} $MultiUser.InstallMode == "AllUsers"
        WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Run" "${{PRODUCTNAME}}" '"$INSTDIR\${{MAINBINARYNAME}}.exe" --autostarted'
        DetailPrint "Registered autostart for all users (HKLM)"
    ${{Else}}
        WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "${{PRODUCTNAME}}" '"$INSTDIR\${{MAINBINARYNAME}}.exe" --autostarted'
        DetailPrint "Registered autostart for current user (HKCU)"
    ${{EndIf}}
    !endif
    !if "${{INSTALLMODE}}" == "perMachine"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Run" "${{PRODUCTNAME}}" '"$INSTDIR\${{MAINBINARYNAME}}.exe" --autostarted'
    DetailPrint "Registered autostart for all users (HKLM)"
    !endif
    !if "${{INSTALLMODE}}" == "currentUser"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "${{PRODUCTNAME}}" '"$INSTDIR\${{MAINBINARYNAME}}.exe" --autostarted'
    DetailPrint "Registered autostart for current user (HKCU)"
    !endif
!macroend

; ============================================================================
; PREUNINSTALL - Runs before uninstallation starts (app may still be running)
; ============================================================================
!macro NSIS_HOOK_PREUNINSTALL
    ; ---- Autostart cleanup ----
    ; Remove autostart BEFORE CheckIfAppIsRunning closes the app,
    ; so it won't relaunch between close and exe deletion.
    DeleteRegValue HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "${{PRODUCTNAME}}"
    DeleteRegValue HKLM "Software\Microsoft\Windows\CurrentVersion\Run" "${{PRODUCTNAME}}"
!macroend

; ============================================================================
; POSTUNINSTALL - Runs after app is closed and exe is deleted
; ============================================================================
!macro NSIS_HOOK_POSTUNINSTALL
    ; Delete GStreamer DLLs that were copied to $INSTDIR during installation.
    ; This runs AFTER CheckIfAppIsRunning has closed the app, so DLLs are unlocked.
    ; List is generated from installers/dlls/*.dll by build.rs.
{delete_lines}

    ; Clean up manifest from older installs
    Delete "$INSTDIR\installed_dlls.txt"

    RMDir /r "$INSTDIR\installers"
    RMDir "$INSTDIR\resources"
    ; Only removes if empty — preserves any user files
    RMDir "$INSTDIR"
!macroend
"#,
        delete_lines = delete_lines,
    );

    // Only write if content changed to avoid unnecessary rebuilds
    let existing = fs::read_to_string(hooks_path).unwrap_or_default();
    if existing != hooks {
        fs::write(hooks_path, &hooks).expect("failed to write windows/hooks.nsi");
    }

    // Re-run build.rs if the DLL directory contents change
    println!("cargo:rerun-if-changed=installers/dlls");
}
